# -*- coding: utf-8 -*-
"""Copy of FML _Project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1agsubNqoUdFxohd1gofWiCLRvKLdT1xT

**FML Course Project 2024**

**Group Members:** Siddhi Shinde(M24CPS008), Rishabh Srivastava(M24CPS007) , Akshat Sahai (M24CPS001)

**Topic:** Bitcoin Price Forecasting with ARIMA

**Step1:** Installing necessary packages
"""

# Install necessary packages
!pip install pandas matplotlib statsmodels scikit-learn tensorflow

# Import the required libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from statsmodels.tsa.arima.model import ARIMA
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

"""**Step2:** Loading the CSV File"""

file_path = '/content/btc_week.csv'
data = pd.read_csv(file_path)

print(data.head())

"""**Step 3:** Exploratory Data Analysis (EDA)"""

data['Date'] = pd.to_datetime(data['Date'])
data.set_index('Date', inplace=True)

plt.figure(figsize=(10,6))
plt.plot(data['Close'], label='Stock Price')
plt.title('Stock Price Over Time')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.show()

"""**Step 4:** ARIMA Model for Time Series Forecasting"""

train_size = int(len(data) * 0.8)
train, test = data[:train_size], data[train_size:]

model = ARIMA(train['Close'], order=(5,1,0))
model_fit = model.fit()

forecast = model_fit.forecast(steps=len(test))

plt.figure(figsize=(10,6))
plt.plot(test.index, test['Close'], label='Actual Prices')
plt.plot(test.index, forecast, label='Forecasted Prices', color='red')
plt.title('ARIMA Model Forecast')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.show()

"""**Step 5:** Evaluation"""

from sklearn.metrics import mean_squared_error

arima_mse = mean_squared_error(test['Close'], forecast)
print('ARIMA MSE:', arima_mse)